package com.odeyalo.kyrie.core;

import java.util.Map;

/**
 * Handler to handle oauth2 supported scope.
 * @version 1.0
 */
public interface Oauth2ScopeHandler {

    /**
     * Create the claims by user info
     * @param user - user that granted permission
     * @return - claims by given scope generated by Oauth2User
     * @see Oauth2User
     */
    Map<String, Object> createClaims(Oauth2User user);

    /**
     * What type of scope this handler support
     * @return - supported scope
     */
    String supportedScope();

}
